<div class="container-fluid bg-primary d-flex align-items-center justify-content-center" style="height:100vh;">

    <div class="loginmodal-container">

        <h1>Faça cadastro agora</h1><br>

        <form class="cadastro-form">
            <input type="file" name="icone" style="display:none" id="icone" accept="image/*">
            <label for="icone" class="icone bg-warning pointer">Escolha sua Imagem</label>
            <input type="text" name="nome" placeholder="Nome">
            <input type="email" name="email" placeholder="Email">
            <input type="email" name="email-repeat" placeholder="Repita o Email">
            <input type="password" name="senha" placeholder="Senha">
            <input type="password" name="senha-repeat" placeholder="Repita a Senha">
            <input type="submit" name="cadastro" class="login loginmodal-submit" value="Cadastrar">
        </form>
                    
        <div class="login-help">
            <a href="./">Login</a> - <a href="#">Trocar a Senha</a>
        </div>

    </div>

</div>