<!DOCTYPE html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<title>Error routing.</title>
</head>
<body>
	<style>
		*{margin:0;padding:0}.error{height:100vh;width:100%;display:flex;justify-content:center;align-items:center;font-family:"Helvetica Neue",sans-serif !important;font-size:32px}red{color:red}
	</style>
	<div class="error">
		<red>Error 404</red> : Rota "<?= $uri ?>" Não Definida!!
	</div>
</body>
</html>