	
	<div class="d-flex justify-content-center align-items-center" style="width:100%;height:10vh;position: absolute;top:90vh">
		<h4>Criado Por: <a href="https://github.com/PaulaoDev/router-khan" target="__blank" style="color:#fff">RouterKhan</a></h4>
	</div>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
	<script src="{{APP_JS}}/app.js"></script>
	<script src="{{APP_JS}}/upload.js"></script>