<div class="container-fluid bg-primary d-flex align-items-center justify-content-center" style="height:100vh;">

    <div class="loginmodal-container">

        <h1>Faça login agora</h1><br>

        <form class="login-form">
            <input type="text" name="email" placeholder="Email">
            <input type="password" name="senha" placeholder="Senha">
            <input type="submit" name="login" class="login loginmodal-submit" value="Login">
        </form>
                    
        <div class="login-help">
            <a href="./registro">Cadastrar</a> - <a href="#">Trocar a Senha</a>
        </div>

    </div>

</div>