<div class="container-fluid bg-primary d-flex align-items-center justify-content-center" style="height:100vh;">

    <div class="jumbotron d-flex align-items-center justify-content-center flex-column">

        <div class="card d-flex align-items-center justify-content-center" style="width: 20rem;height: 40vh">
            <div style="width:130px;height:150px;margin-top: 5vh" class="rounded-circle bg-success d-flex align-items-center justify-content-center">
                <img src="{{image}}" alt="{{nome}} icone" style="width:130px;height:150px;" class="rounded-circle">
            </div>
            <div class="card-block">
                <h4 class="card-title" style="text-transform: capitalize;text-align: center;">{{nome}}</h4>
                <p class="card-text">{{email}}</p>
            </div>
        </div>

        <a class="btn-danger btn btn-lg text-white" style="margin-top:30px;cursor: pointer" href="./logout">Sair</a>

    </div>

</div>